M48
; DRILL file {KiCad 8.0.9} date 2025-05-08T22:04:55-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-08T22:04:55-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0860
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1000
%
G90
G05
T1
X1.475Y-1.3719
T2
X3.875Y-1.3719
X6.275Y-1.3719
M30
